// This file is auto-generated by @hey-api/openapi-ts

export type FeedbackRequest = {
  note?: number;
  comment: string;
  bookId: number;
};

export type BookRequest = {
  id?: number;
  title: string;
  authorName: string;
  isbn: string;
  synopsis: string;
  shareable?: boolean;
};

export type RegistrationRequest = {
  firstname: string;
  lastname: string;
  email: string;
  password: string;
};

export type AuthenticationRequest = {
  email: string;
  password: string;
};

export type AuthenticationResponse = {
  token?: string;
};

export type FeedbackResponse = {
  note?: number;
  comment?: string;
  ownFeedback?: boolean;
};

export type PageResponseFeedbackResponse = {
  content?: Array<FeedbackResponse>;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
};

export type BookResponse = {
  id?: number;
  title?: string;
  authorName?: string;
  isbn?: string;
  synopsis?: string;
  owner?: string;
  cover?: string;
  rate?: number;
  archived?: boolean;
  shareable?: boolean;
};

export type PageResponseBookResponse = {
  content?: Array<BookResponse>;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
};

export type BorrowedBookResponse = {
  id?: number;
  title?: string;
  authorName?: string;
  isbn?: string;
  rate?: number;
  returned?: boolean; // 是否归还
  returnApproved?: boolean; // 书主是否批准归还
};

export type PageResponseBorrowedBookResponse = {
  content?: Array<BorrowedBookResponse>;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  first?: boolean;
  last?: boolean;
};

export type SaveFeedbackData = {
  body: FeedbackRequest;
  path?: never;
  query?: never;
  url: "/feedbacks";
};

export type SaveFeedbackResponses = {
  /**
   * OK
   */
  200: number;
};

export type SaveFeedbackResponse =
  SaveFeedbackResponses[keyof SaveFeedbackResponses];

export type FindAllBooksData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: "/books";
};

export type FindAllBooksResponses = {
  /**
   * OK
   */
  200: PageResponseBookResponse;
};

export type FindAllBooksResponse =
  FindAllBooksResponses[keyof FindAllBooksResponses];

export type SaveData = {
  body: BookRequest;
  path?: never;
  query?: never;
  url: "/books";
};

export type SaveResponses = {
  /**
   * OK
   */
  200: number;
};

export type SaveResponse = SaveResponses[keyof SaveResponses];

export type UploadBookCoverPictureData = {
  body?: {
    file: Blob | File;
  };
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/cover/{book-id}";
};

export type UploadBookCoverPictureResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type UploadBookCoverPictureResponse =
  UploadBookCoverPictureResponses[keyof UploadBookCoverPictureResponses];

export type BorrowBookData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/borrow/{book-id}";
};

export type BorrowBookResponses = {
  /**
   * OK
   */
  200: number;
};

export type BorrowBookResponse = BorrowBookResponses[keyof BorrowBookResponses];

export type RegisterData = {
  body: RegistrationRequest;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type RegisterResponses = {
  /**
   * Accepted
   */
  202: {
    [key: string]: unknown;
  };
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type AuthenticateData = {
  body: AuthenticationRequest;
  path?: never;
  query?: never;
  url: "/auth/authenticate";
};

export type AuthenticateResponses = {
  /**
   * OK
   */
  200: AuthenticationResponse;
};

export type AuthenticateResponse =
  AuthenticateResponses[keyof AuthenticateResponses];

export type UpdateShareableStatusData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/shareable/{book-id}";
};

export type UpdateShareableStatusResponses = {
  /**
   * OK
   */
  200: number;
};

export type UpdateShareableStatusResponse =
  UpdateShareableStatusResponses[keyof UpdateShareableStatusResponses];

export type ReturnBorrowBookData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/borrow/return/{book-id}";
};

export type ReturnBorrowBookResponses = {
  /**
   * OK
   */
  200: number;
};

export type ReturnBorrowBookResponse =
  ReturnBorrowBookResponses[keyof ReturnBorrowBookResponses];

export type ApproveReturnBorrowBookData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/borrow/return/approve/{book-id}";
};

export type ApproveReturnBorrowBookResponses = {
  /**
   * OK
   */
  200: number;
};

export type ApproveReturnBorrowBookResponse =
  ApproveReturnBorrowBookResponses[keyof ApproveReturnBorrowBookResponses];

export type UpdateArchivedStatusData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/archived/{book-id}";
};

export type UpdateArchivedStatusResponses = {
  /**
   * OK
   */
  200: number;
};

export type UpdateArchivedStatusResponse =
  UpdateArchivedStatusResponses[keyof UpdateArchivedStatusResponses];

export type FindAllFeedbacksByBookData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: {
    page?: number;
    size?: number;
  };
  url: "/feedbacks/feedback/{book-id}";
};

export type FindAllFeedbacksByBookResponses = {
  /**
   * OK
   */
  200: PageResponseFeedbackResponse;
};

export type FindAllFeedbacksByBookResponse =
  FindAllFeedbacksByBookResponses[keyof FindAllFeedbacksByBookResponses];

export type FindBookByIdData = {
  body?: never;
  path: {
    "book-id": number;
  };
  query?: never;
  url: "/books/{book-id}";
};

export type FindBookByIdResponses = {
  /**
   * OK
   */
  200: BookResponse;
};

export type FindBookByIdResponse =
  FindBookByIdResponses[keyof FindBookByIdResponses];

export type FindAllReturnedBooksData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: "/books/returned";
};

export type FindAllReturnedBooksResponses = {
  /**
   * OK
   */
  200: PageResponseBorrowedBookResponse;
};

export type FindAllReturnedBooksResponse =
  FindAllReturnedBooksResponses[keyof FindAllReturnedBooksResponses];

export type FindAllBooksByOwnerData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: "/books/owner";
};

export type FindAllBooksByOwnerResponses = {
  /**
   * OK
   */
  200: PageResponseBookResponse;
};

export type FindAllBooksByOwnerResponse =
  FindAllBooksByOwnerResponses[keyof FindAllBooksByOwnerResponses];

export type FindAllBorrowedBooksData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    size?: number;
  };
  url: "/books/borrowed";
};

export type FindAllBorrowedBooksResponses = {
  /**
   * OK
   */
  200: PageResponseBorrowedBookResponse;
};

export type FindAllBorrowedBooksResponse =
  FindAllBorrowedBooksResponses[keyof FindAllBorrowedBooksResponses];

export type ActivateData = {
  body?: never;
  path?: never;
  query: {
    token: string;
  };
  url: "/auth/activate-account";
};

export type ActivateResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL:
    | "http://localhost:8088/api/v1"
    | "https://handi404.github.io"
    | (string & {});
};
